version: "3"
services:
  mongodb:
    image: mongo:3.6
    ports:
      - 27017:27017
    networks:
      - yahuda
    volumes:
      - mongo-data:/var/app/volumes/mongo
    restart: "unless-stopped"
networks:
  ecart:
    driver: bridge
volumes:
  mongo-data:
    driver: local